name = "core"
version = "0.1.0"
defaultTargets = ["core"]

[[lean_lib]]
name = "Klei"

[[lean_exe]]
name = "core"
root = "Main"
moreLinkArgs = ["-L./FFI", "-lklei_socket", "-Wl,-rpath,./FFI"]

[[lean_exe]]
name = "test-socket"
root = "TestSocket"
moreLinkArgs = ["-L./FFI", "-lklei_socket", "-Wl,-rpath,./FFI"]
